substitutions:
  _IMAGE: "gcr.io/carpool-app-470818/carpool-web"
  _VITE_API_BASE: "https://carpool-api-dzxkfcfuiq-uc.a.run.app"
  _SERVICE: "carpool-web"
  _REGION: "us-central1"
  _VITE_GOOGLE_MAPS_API_KEY: "AIzaSyCtD8BGnZalGT44CF7qWuj_W2MzlNZow2k"
  _VITE_GOOGLE_API_KEY: "AIzaSyCtD8BGnZalGT44CF7qWuj_W2MzlNZow2k"
  _VITE_GOOGLE_CLIENT_ID: "37218666122-q4qjsa38e8eojhnl1q8k0s6sp4ml6dlf.apps.googleusercontent.com"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: ['build', '-f', 'web/Dockerfile.web', '--build-arg', 'VITE_API_BASE=${_VITE_API_BASE}', '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}', '--build-arg', 'VITE_GOOGLE_API_KEY=${_VITE_GOOGLE_API_KEY}', '--build-arg', 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}', '-t', '${_IMAGE}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args: ['push', '${_IMAGE}']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Allow unauthenticated invoke'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud beta run services add-iam-policy-binding ${_SERVICE} \
          --region=${_REGION} \
          --member=allUsers \
          --role=roles/run.invoker || true
images:
  - '${_IMAGE}'
