substitutions:
  _VITE_API_BASE: ""
  _SERVICE: ""
  _REGION: ""
  _VITE_GOOGLE_MAPS_API_KEY: ""
  _VITE_GOOGLE_API_KEY: ""

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: ['build', '-f', 'web/Dockerfile.web', '--build-arg', 'VITE_API_BASE=${_VITE_API_BASE}', '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}', '--build-arg', 'VITE_GOOGLE_API_KEY=${_VITE_GOOGLE_API_KEY}', '-t', '${_IMAGE}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args: ['push', '${_IMAGE}']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Allow unauthenticated invoke'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud beta run services add-iam-policy-binding ${_SERVICE} \
          --region=${_REGION} \
          --member=allUsers \
          --role=roles/run.invoker || true
images:
  - '${_IMAGE}'
