steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: ['build', '-f', 'Dockerfile.api', '-t', '${_IMAGE}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args: ['push', '${_IMAGE}']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8000
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Allow unauthenticated invoke'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud beta run services add-iam-policy-binding ${_SERVICE} \
          --region=${_REGION} \
          --member=allUsers \
          --role=roles/run.invoker || true
images:
  - '${_IMAGE}'
